# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/root
  block:

  - name: CIS | Configure the root user account
    become: true
    ansible.builtin.user:
      name: 'root'
      shell: '/bin/bash'
      uid: 0
      group: 'root'
      expires: 0
      home: '/root'
      password: "{{ root_password }}"
      password_expire_max: 99999
      password_expire_min: 0

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_root'
