# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/root
  block:

  - name: CIS | Ensure inactive password lock is 30 days or less (check)
    become: true
    ansible.builtin.shell:
      cmd: "passwd -S root | awk '{print $7}'"
    check_mode: false
    changed_when: password_inactive.stdout != '30'
    register: password_inactive

  - name: CIS | Ensure inactive password lock is 30 days or less (set)
    become: true
    ansible.builtin.command:
      cmd: "chage --inactive '{{ root_password_inactive }}' root"
    when: password_inactive is changed

  - name: CIS | Configure the root user account
    become: true
    ansible.builtin.user:
      name: 'root'
      shell: '/bin/bash'
      uid: 0
      group: 'root'
      expires: -1
      home: '/root'
      password: "{{ root_password }}"
      password_expire_max: "{{ root_password_maxdays }}"
      password_expire_min: "{{ root_password_mindays }}"

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_root'
